import json

# The HTML content, built as a list of lines
lines = []
lines.append('<!DOCTYPE html>')
lines.append('<html lang="zh-CN">')
lines.append('<head>')
lines.append('<meta charset="UTF-8">')
lines.append('<meta name="viewport" content="width=device-width, initial-scale=1.0">')
lines.append('<title>TCG 卡牌识别</title>')
lines.append('<style>')
lines.append('  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }')
lines.append('  :root { --bg: #0f1117; --surface: #1a1d28; --surface2: #232738; --border: #2e3348; --text: #e1e4ed; --text2: #8b8fa3; --accent: #5b8def; --green: #34d399; --orange: #f59e0b; --radius: 8px; }')
lines.append('  body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", system-ui, sans-serif; background: var(--bg); color: var(--text); min-height: 100vh; display: flex; flex-direction: column; align-items: center; }')
lines.append('  .container { width: 100%; max-width: 640px; padding: 24px 16px; }')
lines.append('  header { display: flex; align-items: center; gap: 12px; margin-bottom: 16px; }')
lines.append('  header h1 { font-size: 20px; font-weight: 600; letter-spacing: -0.01em; }')
lines.append('  .badge { font-size: 11px; color: var(--text2); background: var(--surface2); padding: 2px 8px; border-radius: 4px; border: 1px solid var(--border); }')
lines.append('  .status-dot { display: inline-block; width: 8px; height: 8px; border-radius: 50%; margin-left: auto; background: var(--text2); }')
lines.append('  .status-dot.ok { background: var(--green); }')
lines.append('  .status-dot.err { background: #f87171; }')
lines.append('  .tab-bar { display: flex; gap: 0; margin-bottom: 20px; background: var(--surface); border-radius: var(--radius); border: 1px solid var(--border); overflow: hidden; }')
lines.append('  .tab { flex: 1; padding: 10px 16px; text-align: center; font-size: 14px; font-weight: 500; color: var(--text2); background: transparent; border: none; cursor: pointer; transition: background 0.15s, color 0.15s; position: relative; }')
lines.append('  .tab:hover { color: var(--text); background: var(--surface2); }')
lines.append('  .tab.active { color: var(--text); background: var(--surface2); }')
lines.append('  .tab.active::after { content: ""; position: absolute; bottom: 0; left: 20%; right: 20%; height: 2px; background: var(--accent); border-radius: 1px; }')
lines.append('  .tab-content { display: none; }')
lines.append('  .tab-content.active { display: block; }')
lines.append('  .drop-zone { border: 2px dashed var(--border); border-radius: var(--radius); padding: 48px 24px; text-align: center; cursor: pointer; transition: border-color 0.2s, background 0.2s; background: var(--surface); }')
lines.append('  .drop-zone:hover, .drop-zone.drag-over { border-color: var(--accent); background: var(--surface2); }')
lines.append('  .drop-zone .icon { font-size: 36px; margin-bottom: 12px; opacity: 0.6; }')
lines.append('  .drop-zone p { color: var(--text2); font-size: 14px; }')
lines.append('  .drop-zone .hint { font-size: 12px; color: var(--text2); margin-top: 8px; opacity: 0.5; }')
lines.append('  .preview-area { display: none; margin-top: 16px; position: relative; }')
lines.append('  .preview-area.show { display: block; }')
lines.append('  .preview-area .img-container { position: relative; display: inline-block; width: 100%; }')
lines.append('  .preview-area .img-container img { width: 100%; max-height: 320px; object-fit: contain; border-radius: var(--radius); background: var(--surface); border: 1px solid var(--border); display: block; }')
lines.append('  .preview-area .img-container canvas { position: absolute; top: 0; left: 0; width: 100%; height: 100%; pointer-events: none; }')
lines.append('  .preview-actions { display: flex; gap: 8px; margin-top: 8px; justify-content: flex-end; flex-wrap: wrap; }')
lines.append('  .btn { display: inline-flex; align-items: center; gap: 6px; padding: 8px 16px; border-radius: 6px; border: 1px solid var(--border); background: var(--surface2); color: var(--text); font-size: 13px; cursor: pointer; transition: background 0.15s; }')
lines.append('  .btn:hover { background: var(--border); }')
lines.append('  .btn.primary { background: var(--accent); border-color: var(--accent); color: #fff; }')
lines.append('  .btn.primary:hover { opacity: 0.9; }')
lines.append('  .btn.ocr { background: var(--orange); border-color: var(--orange); color: #fff; }')
lines.append('  .btn.ocr:hover { opacity: 0.9; }')
lines.append('  .btn:disabled { opacity: 0.4; cursor: not-allowed; }')
lines.append('  .btn .spinner { display: none; width: 14px; height: 14px; border: 2px solid rgba(255,255,255,0.3); border-top-color: #fff; border-radius: 50%; animation: spin 0.6s linear infinite; }')
lines.append('  .btn.loading .spinner { display: inline-block; }')
lines.append('  .btn.loading .label { display: none; }')
lines.append('  @keyframes spin { to { transform: rotate(360deg); } }')
lines.append('  .search-result { display: none; margin-top: 16px; }')
lines.append('  .search-result.show { display: block; }')
lines.append('  .search-result .card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 16px; overflow: hidden; }')
lines.append('  .search-header { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }')
lines.append('  .search-header .label { font-size: 13px; font-weight: 600; color: var(--text); }')
lines.append('  .search-header .time { font-size: 12px; color: var(--text2); margin-left: auto; }')
lines.append('  .top5-list { list-style: none; display: flex; flex-direction: column; gap: 6px; }')
lines.append('  .top5-item { display: flex; align-items: center; gap: 10px; padding: 10px 12px; border-radius: 6px; background: var(--surface2); border: 1px solid transparent; }')
lines.append('  .top5-item:first-child { border-color: rgba(91,141,239,0.4); }')
lines.append('  .top5-rank { font-size: 12px; font-weight: 700; min-width: 20px; text-align: center; color: var(--text2); }')
lines.append('  .top5-item:first-child .top5-rank { color: var(--accent); font-size: 14px; }')
lines.append('  .top5-item img { width: 48px; height: 48px; object-fit: cover; border-radius: 4px; background: var(--bg); border: 1px solid var(--border); flex-shrink: 0; }')
lines.append('  .top5-id { font-family: monospace; font-size: 14px; font-weight: 500; flex: 1; }')
lines.append('  .top5-score { font-family: monospace; font-size: 13px; color: var(--text2); }')
lines.append('  .top5-bar-outer { width: 60px; height: 6px; background: var(--border); border-radius: 3px; overflow: hidden; }')
lines.append('  .top5-bar-inner { height: 100%; border-radius: 3px; background: var(--accent); transition: width 0.4s ease; }')
lines.append('  .top5-item:first-child .top5-bar-inner { background: var(--green); }')
lines.append('  .top5-empty { color: var(--text2); font-size: 13px; text-align: center; padding: 24px; }')
lines.append('  .result-detail { margin-top: 12px; padding-top: 12px; border-top: 1px solid var(--border); }')
lines.append('  .result-detail .label { font-size: 11px; color: var(--text2); margin-bottom: 4px; }')
lines.append('  .result-detail .value { font-size: 13px; font-family: monospace; color: var(--text2); word-break: break-all; }')
lines.append('  .ocr-result { display: none; margin-top: 16px; }')
lines.append('  .ocr-result.show { display: block; }')
lines.append('  .ocr-result .card { background: var(--surface); border: 1px solid var(--border); border-radius: var(--radius); padding: 16px; }')
lines.append('  .ocr-header { display: flex; align-items: center; gap: 8px; margin-bottom: 12px; }')
lines.append('  .ocr-header .label { font-size: 13px; font-weight: 600; color: var(--text); }')
lines.append('  .ocr-header .time { font-size: 12px; color: var(--text2); margin-left: auto; }')
lines.append('  .ocr-header .count { font-size: 12px; color: var(--text2); }')
lines.append('  .ocr-block-list { list-style: none; display: flex; flex-direction: column; gap: 4px; max-height: 300px; overflow-y: auto; }')
lines.append('  .ocr-block-item { display: flex; align-items: center; gap: 8px; padding: 8px 10px; border-radius: 4px; background: var(--surface2); font-size: 13px; }')
lines.append('  .ocr-block-text { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }')
lines.append('  .ocr-block-conf { font-family: monospace; font-size: 11px; color: var(--text2); min-width: 40px; text-align: right; }')
lines.append('  .ocr-block-conf.high { color: var(--green); }')
lines.append('  .ocr-block-conf.mid { color: var(--orange); }')
lines.append('  .ocr-block-conf.low { color: #f87171; }')
lines.append('  .ocr-full-text { margin-top: 12px; }')
lines.append('  .ocr-full-text label { font-size: 11px; color: var(--text2); display: block; margin-bottom: 4px; }')
lines.append('  .ocr-full-text textarea { width: 100%; min-height: 80px; max-height: 200px; padding: 10px; border-radius: 4px; border: 1px solid var(--border); background: var(--bg); color: var(--text); font-family: monospace; font-size: 13px; resize: vertical; line-height: 1.5; }')
lines.append('  .ocr-full-text textarea:focus { outline: none; border-color: var(--accent); }')
lines.append('  .ocr-empty { color: var(--text2); font-size: 13px; text-align: center; padding: 24px; }')
lines.append('  .history { margin-top: 24px; }')
lines.append('  .history h2 { font-size: 14px; font-weight: 500; color: var(--text2); margin-bottom: 8px; }')
lines.append('  .history-list { display: flex; flex-direction: column; gap: 4px; }')
lines.append('  .history-item { display: flex; align-items: center; gap: 8px; padding: 8px 12px; background: var(--surface); border-radius: 6px; font-size: 13px; cursor: pointer; transition: background 0.15s; }')
lines.append('  .history-item:hover { background: var(--surface2); }')
lines.append('  .h-rank { font-size: 11px; font-weight: 600; color: var(--text2); min-width: 12px; }')
lines.append('  .history-item .h-name { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }')
lines.append('  .history-item .h-score { font-family: monospace; color: var(--text2); font-size: 12px; }')
lines.append('  .history-empty { color: var(--text2); font-size: 13px; text-align: center; padding: 16px; }')
lines.append('  .spinner-full { display: none; justify-content: center; align-items: center; padding: 32px; }')
lines.append('  .spinner-full.show { display: flex; }')
lines.append('  .spinner-full .ring { width: 24px; height: 24px; border: 3px solid var(--border); border-top-color: var(--accent); border-radius: 50%; animation: spin 0.6s linear infinite; }')
lines.append('  @media (max-width: 480px) { .container { padding: 16px 12px; } .tab { font-size: 13px; padding: 8px 12px; } }')
lines.append('</style>')
lines.append('</head>')
lines.append('<body>')
lines.append('<div class="container">')
lines.append('  <header>')
lines.append('    <h1>TCG 卡牌识别</h1>')
lines.append('    <span class="badge">v0.2</span>')
lines.append('    <span class="status-dot" id="statusDot" title="服务器状态"></span>')
lines.append('  </header>')
lines.append('  <div class="tab-bar" id="tabBar">')
lines.append('    <button class="tab active" data-tab="search">\U0001F50D 视觉搜索</button>')
lines.append('    <button class="tab" data-tab="ocr">\U0001F4DD 文字识别</button>')
lines.append('  </div>')
lines.append('  <div class="tab-content active" id="tabSearch">')
lines.append('    <div class="drop-zone" id="dropZone">')
lines.append('      <div class="icon">\U0001F4F7</div>')
lines.append('      <p>拖放卡牌图片到这里，或点击选择文件</p>')
lines.append('      <div class="hint">支持 JPG / PNG，最大 10MB</div>')
lines.append('      <input type="file" id="fileInput" accept="image/jpeg,image/png" hidden>')
lines.append('    </div>')
lines.append('    <div class="preview-area" id="previewArea">')
lines.append('      <div class="img-container">')
lines.append('        <img id="previewImg" alt="预览">')
lines.append('        <canvas id="bboxCanvas"></canvas>')
lines.append('      </div>')
lines.append('      <div class="preview-actions">')
lines.append('        <button class="btn" id="clearBtn">\u2716 清除</button>')
lines.append('        <button class="btn primary" id="searchBtn">')
lines.append('          <span class="spinner"></span>')
lines.append('          <span class="label">\U0001F50D 搜索 Top-5</span>')
lines.append('        </button>')
lines.append('        <button class="btn ocr" id="ocrBtn" style="display:none">')
lines.append('          <span class="spinner"></span>')
lines.append('          <span class="label">\U0001F4DD 识别文字</span>')
lines.append('        </button>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('    <div class="spinner-full" id="loadingSpinner">')
lines.append('      <div class="ring"></div>')
lines.append('    </div>')
lines.append('    <div class="search-result" id="searchResult">')
lines.append('      <div class="card">')
lines.append('        <div class="search-header">')
lines.append('          <span class="label">\U0001F50D 搜索结果</span>')
lines.append('          <span class="time" id="searchTime"></span>')
lines.append('        </div>')
lines.append('        <div class="top5-list" id="top5List">')
lines.append('          <div class="top5-empty">无结果</div>')
lines.append('        </div>')
lines.append('        <div class="result-detail">')
lines.append('          <div class="label">原始响应</div>')
lines.append('          <div class="value" id="resultRaw"></div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('    <div class="ocr-result" id="ocrResult">')
lines.append('      <div class="card">')
lines.append('        <div class="ocr-header">')
lines.append('          <span class="label">\U0001F4DD 识别结果</span>')
lines.append('          <span class="count" id="ocrBlockCount"></span>')
lines.append('          <span class="time" id="ocrTime"></span>')
lines.append('        </div>')
lines.append('        <div class="ocr-block-list" id="ocrBlockList">')
lines.append('          <div class="ocr-empty">未检测到文字</div>')
lines.append('        </div>')
lines.append('        <div class="ocr-full-text">')
lines.append('          <label for="ocrFullText">全文</label>')
lines.append('          <textarea id="ocrFullText" readonly></textarea>')
lines.append('        </div>')
lines.append('        <div class="result-detail">')
lines.append('          <div class="label">原始响应</div>')
lines.append('          <div class="value" id="ocrRaw"></div>')
lines.append('        </div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('    <div class="history">')
lines.append('      <h2>查询历史</h2>')
lines.append('      <div class="history-list" id="historyList">')
lines.append('        <div class="history-empty">暂无记录</div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('  <div class="tab-content" id="tabOcr">')
lines.append('    <div class="history" id="ocrHistory">')
lines.append('      <h2>OCR 历史</h2>')
lines.append('      <div class="history-list" id="ocrHistoryList">')
lines.append('        <div class="history-empty">暂无记录</div>')
lines.append('      </div>')
lines.append('    </div>')
lines.append('  </div>')
lines.append('</div>')
lines.append('<script>')
lines.append('var API_BASE = "";')
lines.append('var dropZone = document.getElementById("dropZone");')
lines.append('var fileInput = document.getElementById("fileInput");')
lines.append('var previewArea = document.getElementById("previewArea");')
lines.append('var previewImg = document.getElementById("previewImg");')
lines.append('var bboxCanvas = document.getElementById("bboxCanvas");')
lines.append('var clearBtn = document.getElementById("clearBtn");')
lines.append('var searchBtn = document.getElementById("searchBtn");')
lines.append('var ocrBtn = document.getElementById("ocrBtn");')
lines.append('var loadingSpinner = document.getElementById("loadingSpinner");')
lines.append('var searchResult = document.getElementById("searchResult");')
lines.append('var ocrResult = document.getElementById("ocrResult");')
lines.append('var searchTime = document.getElementById("searchTime");')
lines.append('var top5List = document.getElementById("top5List");')
lines.append('var resultRaw = document.getElementById("resultRaw");')
lines.append('var ocrBlockList = document.getElementById("ocrBlockList");')
lines.append('var ocrBlockCount = document.getElementById("ocrBlockCount");')
lines.append('var ocrTime = document.getElementById("ocrTime");')
lines.append('var ocrFullText = document.getElementById("ocrFullText");')
lines.append('var ocrRaw = document.getElementById("ocrRaw");')
lines.append('var statusDot = document.getElementById("statusDot");')
lines.append('var historyList = document.getElementById("historyList");')
lines.append('var ocrHistoryList = document.getElementById("ocrHistoryList");')
lines.append('var tabBar = document.getElementById("tabBar");')
lines.append('var currentFile = null;')
lines.append('var currentTab = "search";')
lines.append('var MAX_HISTORY = 20;')
lines.append('var searchHistory = loadHistory("tcg_history");')
lines.append('var ocrHistory = loadHistory("tcg_ocr_history");')
lines.append('function loadHistory(key) { try { var p = JSON.parse(localStorage.getItem(key) || "[]"); return Array.isArray(p) ? p : []; } catch (e) { return []; } }')
lines.append('function saveHistory(key, data) { try { localStorage.setItem(key, JSON.stringify(data.slice(0, MAX_HISTORY))); } catch (e) {} }')
lines.append('function escapeHtml(s) { if (typeof s !== "string") return String(s); var d = document.createElement("div"); d.textContent = s; return d.innerHTML; }')
lines.append('function showPreview(dataUrl, fileName) { previewImg.src = dataUrl; previewArea.classList.add("show"); dropZone.style.display = "none"; currentFile = { dataUrl: dataUrl, fileName: fileName }; searchResult.classList.remove("show"); ocrResult.classList.remove("show"); bboxCanvas.getContext("2d").clearRect(0, 0, bboxCanvas.width, bboxCanvas.height); updateActionButtons(); }')
lines.append('function resetUpload() { previewArea.classList.remove("show"); dropZone.style.display = ""; previewImg.src = ""; bboxCanvas.getContext("2d").clearRect(0, 0, bboxCanvas.width, bboxCanvas.height); currentFile = null; fileInput.value = ""; searchResult.classList.remove("show"); ocrResult.classList.remove("show"); }')
lines.append('function updateActionButtons() { if (currentTab === "search") { searchBtn.style.display = ""; ocrBtn.style.display = "none"; } else { searchBtn.style.display = "none"; ocrBtn.style.display = ""; } }')
lines.append('tabBar.addEventListener("click", function(e) { var tab = e.target.closest(".tab"); if (!tab) return; var tabName = tab.dataset.tab; if (tabName === currentTab) return; document.querySelectorAll(".tab").forEach(function(t) { t.classList.remove("active"); }); tab.classList.add("active"); document.querySelectorAll(".tab-content").forEach(function(tc) { tc.classList.remove("active"); }); document.getElementById("tab" + tabName.charAt(0).toUpperCase() + tabName.slice(1)).classList.add("active"); currentTab = tabName; updateActionButtons(); if (tabName === "search") { ocrResult.classList.remove("show"); } else { searchResult.classList.remove("show"); } });')
lines.append('function renderHistory() { if (searchHistory.length === 0) { historyList.innerHTML = "<div class=\\"history-empty\\">\u6682\u65E0\u8BB0\u5F55</div>"; return; } var html = ""; for (var i = 0; i < searchHistory.length; i++) { var h = searchHistory[i]; var rank = h.top1 ? "#" + h.top1.rank : "#?"; var name = h.fileName || "unknown"; var score = h.top1 ? h.top1.score.toFixed(4) : "-"; html += "<div class=\\"history-item\\" onclick=\\"replayHistory(" + i + ')"' + '">' + "<span class=\\"h-rank\\">" + rank + "</span><span class=\\"h-name\\">" + escapeHtml(name) + "</span><span class=\\"h-score\\">" + score + "</span></div>"; } historyList.innerHTML = html; }')
lines.append('function replayHistory(idx) { var h = searchHistory[idx]; if (h && h.dataUrl) { showPreview(h.dataUrl, h.fileName); displaySearchResult(h.response, h.duration); } }')
lines.append('function renderOcrHistory() { if (ocrHistory.length === 0) { ocrHistoryList.innerHTML = "<div class=\\"history-empty\\">\u6682\u65E0\u8BB0\u5F55</div>"; return; } var html = ""; for (var i = 0; i < ocrHistory.length; i++) { var h = ocrHistory[i]; var count = h.response ? (h.response.total_blocks || 0) : 0; var name = h.fileName || "unknown"; html += "<div class=\\"history-item\\" onclick=\\"replayOcrHistory(" + i + ')"' + '">' + "<span class=\\"h-rank\\">" + count + "\u5757</span><span class=\\"h-name\\">" + escapeHtml(name) + "</span><span class=\\"h-score\\">" + (h.response ? (h.response.ocr_time_ms || 0).toFixed(0) + "ms" : "") + "</span></div>"; } ocrHistoryList.innerHTML = html; }')
lines.append('function replayOcrHistory(idx) { var h = ocrHistory[idx]; if (h && h.dataUrl) { document.querySelector("' + '".tab[data-tab=\\"ocr\\"]").click(); showPreview(h.dataUrl, h.fileName); displayOcrResult(h.response, h.duration); } }')
lines.append('function displaySearchResult(data, durationMs) { searchTime.textContent = (durationMs / 1000).toFixed(2) + "s"; var results = data.results || []; if (results.length === 0) { top5List.innerHTML = "<div class=\\"top5-empty\\">\u65E0\u7ED3\u679C</div>"; } else { var maxScore = results[0].score; var html = ""; for (var k = 0; k < results.length; k++) { var r = results[k]; var barPct = Math.min(100, (r.score / maxScore) * 100); html += "<div class=\\"top5-item\\"><span class=\\"top5-rank\\">#" + r.rank + "</span><img src=\\"/v1/images/" + encodeURIComponent(r.card_id) + "\\" alt=\\"" + escapeHtml(r.card_id) + "\\" loading=\\"lazy\\" onerror=\\"this.style.display=\\'none\\'\\"><span class=\\"top5-id\\">" + escapeHtml(r.card_id) + "</span><span class=\\"top5-score\\">" + r.score.toFixed(4) + "</span><div class=\\"top5-bar-outer\\"><div class=\\"top5-bar-inner\\" style=\\"width:" + barPct + "%\\"></div></div></div>"; } top5List.innerHTML = html; } resultRaw.textContent = JSON.stringify(data, null, 2); searchResult.classList.add("show"); if (currentFile) { searchHistory.unshift({ fileName: currentFile.fileName, dataUrl: currentFile.dataUrl, top1: results.length > 0 ? results[0] : null, response: data, duration: durationMs, timestamp: Date.now() }); saveHistory("tcg_history", searchHistory); renderHistory(); } }')
lines.append('function drawBoundingBoxes(imgElement, canvas, blocks, originalWidth, originalHeight) { var ctx = canvas.getContext("2d"); var rect = imgElement.getBoundingClientRect(); canvas.width = rect.width; canvas.height = rect.height; ctx.drawImage(imgElement, 0, 0, canvas.width, canvas.height); var scaleX = canvas.width / originalWidth; var scaleY = canvas.height / originalHeight; ctx.strokeStyle = "#f59e0b"; ctx.lineWidth = 2; ctx.font = "12px sans-serif"; ctx.fillStyle = "rgba(245, 158, 11, 0.8)"; for (var i = 0; i < blocks.length; i++) { var bbox = blocks[i].bbox; if (!bbox || bbox.length < 4) continue; var pts = bbox.map(function(p) { return [p[0] * scaleX, p[1] * scaleY]; }); ctx.beginPath(); ctx.moveTo(pts[0][0], pts[0][1]); for (var j = 1; j < pts.length; j++) { ctx.lineTo(pts[j][0], pts[j][1]); } ctx.closePath(); ctx.stroke(); var label = (i + 1) + ""; ctx.fillText(label, pts[0][0] + 2, pts[0][1] - 4); } }')
lines.append('function displayOcrResult(data, durationMs) { ocrTime.textContent = (data.ocr_time_ms || 0).toFixed(0) + "ms"; var blocks = data.blocks || []; ocrBlockCount.textContent = blocks.length + " \u4E2A\u6587\u672C\u5757"; if (blocks.length === 0) { ocrBlockList.innerHTML = "<div class=\\"ocr-empty\\">\u672A\u68C0\u6D4B\u5230\u6587\u5B57</div>"; } else { var html = ""; for (var k = 0; k < blocks.length; k++) { var b = blocks[k]; var confClass = "mid"; if (b.confidence >= 0.9) confClass = "high"; else if (b.confidence < 0.7) confClass = "low"; html += "<div class=\\"ocr-block-item\\"><span class=\\"ocr-block-text\\">" + escapeHtml(b.text) + "</span><span class=\\"ocr-block-conf " + confClass + "\\">" + (b.confidence * 100).toFixed(0) + "%</span></div>"; } ocrBlockList.innerHTML = html; } ocrFullText.value = data.full_text || ""; ocrRaw.textContent = JSON.stringify(data, null, 2); ocrResult.classList.add("show"); if (blocks.length > 0) { var tempImg = new Image(); tempImg.onload = function() { var ow = tempImg.naturalWidth || tempImg.width; var oh = tempImg.naturalHeight || tempImg.height; drawBoundingBoxes(previewImg, bboxCanvas, blocks, ow, oh); }; tempImg.src = currentFile.dataUrl; } if (currentFile) { ocrHistory.unshift({ fileName: currentFile.fileName, dataUrl: currentFile.dataUrl, response: data, duration: durationMs, timestamp: Date.now() }); saveHistory("tcg_ocr_history", ocrHistory); renderOcrHistory(); } }')
lines.append('async function doSearch() { if (!currentFile) return; searchBtn.classList.add("loading"); searchBtn.disabled = true; loadingSpinner.classList.add("show"); searchResult.classList.remove("show"); ocrResult.classList.remove("show"); var resp = await fetch(currentFile.dataUrl); var blob = await resp.blob(); var formData = new FormData(); formData.append("file", blob, currentFile.fileName || "card.jpg"); var t0 = performance.now(); try { var res = await fetch(API_BASE + "/v1/search", { method: "POST", body: formData }); var dur = performance.now() - t0; var data = await res.json(); displaySearchResult(data, dur); } catch (err) { var dur = performance.now() - t0; displaySearchResult({ status: "error", results: [], message: err.message }, dur); } finally { searchBtn.classList.remove("loading"); searchBtn.disabled = false; loadingSpinner.classList.remove("show"); } }')
lines.append('async function doOcr() { if (!currentFile) return; ocrBtn.classList.add("loading"); ocrBtn.disabled = true; loadingSpinner.classList.add("show"); searchResult.classList.remove("show"); ocrResult.classList.remove("show"); var resp = await fetch(currentFile.dataUrl); var blob = await resp.blob(); var formData = new FormData(); formData.append("file", blob, currentFile.fileName || "card.jpg"); var t0 = performance.now(); try { var res = await fetch(API_BASE + "/v1/ocr", { method: "POST", body: formData }); var dur = performance.now() - t0; var data = await res.json(); displayOcrResult(data, dur); } catch (err) { var dur = performance.now() - t0; displayOcrResult({ status: "error", blocks: [], full_text: "", ocr_time_ms: dur, message: err.message }, dur); } finally { ocrBtn.classList.remove("loading"); ocrBtn.disabled = false; loadingSpinner.classList.remove("show"); } }')
lines.append('async function checkHealth() { try { var res = await fetch(API_BASE + "/v1/health"); if (res.ok) { statusDot.className = "status-dot ok"; statusDot.title = "Server OK"; } else { statusDot.className = "status-dot err"; statusDot.title = "Server error"; } } catch (e) { statusDot.className = "status-dot err"; statusDot.title = "Server unreachable"; } }')
lines.append('function handleFile(file) { if (file && file.type.startsWith("image/")) { var reader = new FileReader(); reader.onload = function(ev) { showPreview(ev.target.result, file.name); }; reader.readAsDataURL(file); } }')
lines.append('dropZone.addEventListener("click", function() { fileInput.click(); });')
lines.append('dropZone.addEventListener("dragover", function(e) { e.preventDefault(); dropZone.classList.add("drag-over"); });')
lines.append('dropZone.addEventListener("dragleave", function() { dropZone.classList.remove("drag-over"); });')
lines.append('dropZone.addEventListener("drop", function(e) { e.preventDefault(); dropZone.classList.remove("drag-over"); handleFile(e.dataTransfer.files[0]); });')
lines.append('fileInput.addEventListener("change", function() { handleFile(fileInput.files[0]); });')
lines.append('clearBtn.addEventListener("click", resetUpload);')
lines.append('searchBtn.addEventListener("click", doSearch);')
lines.append('ocrBtn.addEventListener("click", doOcr);')
lines.append('checkHealth();')
lines.append('setInterval(checkHealth, 30000);')
lines.append('renderHistory();')
lines.append('renderOcrHistory();')
lines.append('</script>')
lines.append('</body>')
lines.append('</html>')

html = '\n'.join(lines)
path = r'D:\Code2026\tcg-embedding-service\app\static\index.html'
with open(path, 'w', encoding='utf-8') as f:
    f.write(html)
print(f'Written {len(html)} bytes')
