import os, json, sys

lines = []
lines.append("import os")
lines.append("import sys")
lines.append("import io")
lines.append("import json")
lines.append("import time")
lines.append("import logging")
lines.append("import base64")
lines.append("")
lines.append("import numpy as np")
lines.append("import torch")
lines.append("import faiss")
lines.append("from fastapi import FastAPI, UploadFile, File, HTTPException")
lines.append("from fastapi.responses import FileResponse")
lines.append("from fastapi.middleware.cors import CORSMiddleware")
lines.append("from pydantic import BaseModel")
lines.append("from PIL import Image, ImageFile")
lines.append("from sentence_transformers import SentenceTransformer")
lines.append("import uvicorn")
lines.append("")
lines.append("ImageFile.LOAD_TRUNCATED_IMAGES = True")
lines.append("")
lines.append("ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))")
lines.append("sys.path.insert(0, os.path.join(ROOT, \"script_temp\"))")
lines.append("from preprocess import orientation_candidates, to_model_input, preprocess_query, preprocess_for_ocr, preprocess_for_search")
lines.append("from preprocess_ocr import OCRPreprocessor")
lines.append("from ppocr_v4_engine import PPOCRv4Engine")
lines.append("")
lines.append("# ---- Logging ----")
lines.append("logging.basicConfig(level=logging.INFO, format=\"%(asctime)s [%(levelname)s] %(message)s\")")
lines.append("log = logging.getLogger(__name__)")
lines.append("")
lines.append("# ---- Constants ----")
lines.append("MEAN = np.array([0.485, 0.456, 0.406], dtype=np.float32)")
lines.append("STD = np.array([0.229, 0.224, 0.225], dtype=np.float32)")
lines.append("MAX_FILE_SIZE = 10 * 1024 * 1024")
lines.append("")
lines.append("TAU = float(os.environ.get(\"MATCH_TAU\", \"0.775\"))")
lines.append("MARGIN = float(os.environ.get(\"MATCH_MARGIN\", \"0.02\"))")
lines.append("")
lines.append("# ---- BGE text embedding constants ----")
lines.append("BGE_MODEL_NAME = \"BAAI/bge-small-en-v1.5\"")
lines.append("BGE_QUERY_PREFIX = \"Represent this sentence for searching relevant passages: \"")
lines.append("")
lines.append("# ---- OCR retry config ----")
lines.append("OCR_RETRY_CONF = {\"min_blocks\": 2, \"retry_180\": True}")
lines.append("")
lines.append("# ---- Pokemon data paths ----")
lines.append("POKEMON_IMAGES_DIR = os.path.join(ROOT, \"category_cards_search\", \"03_Pokemon\", \"images\")")
lines.append("POKEMON_INDEX_DIR = os.path.join(ROOT, \"pokemon-index\")")
lines.append("TEXT_INDEX_DIR = os.path.join(ROOT, \"text-index\")")
lines.append("PRODUCTS_JSONL = os.path.join(ROOT, \"category_cards_search\", \"03_Pokemon\", \"products.jsonl\")")
lines.append("")
lines.append("# ---- Global state ----")
lines.append("model = None")
lines.append("faiss_index = None")
lines.append("index_ids = None")
lines.append("index_version = \"\"")
lines.append("ocr_engine = None")
lines.append("text_model = None")
lines.append("text_index = None")
lines.append("text_ids = None")
lines.append("products = None")
lines.append("")
lines.append("# ---- Pydantic models ----")
lines.append("class HealthResponse(BaseModel):")
lines.append("    status: str")
lines.append("    index_size: int")
lines.append("    embedding_dim: int")
lines.append("    version: str")
lines.append("")
lines.append("class MatchResponse(BaseModel):")
lines.append("    status: str")
lines.append("    card_id: str | None = None")
lines.append("    score: float | None = None")
lines.append("    margin: float | None = None")
lines.append("    top2_id: str | None = None")
lines.append("    top2_score: float | None = None")
lines.append("")
lines.append("class SearchResult(BaseModel):")
lines.append("    rank: int")
lines.append("    card_id: str")
lines.append("    score: float")
lines.append("")
lines.append("class SearchResponse(BaseModel):")
lines.append("    status: str")
lines.append("    query_time_ms: float")
lines.append("    results: list[SearchResult]")
lines.append("    preprocessed_image: str | None = None")
lines.append("    warnings: list[str] = []")
lines.append("")
lines.append("class OCRBlock(BaseModel):")
lines.append("    text: str")
lines.append("    confidence: float")
lines.append("    bbox: list[list[float]]")
lines.append("")
lines.append("class OCRResponse(BaseModel):")
lines.append("    status: str")
lines.append("    ocr_time_ms: float")
lines.append("    total_blocks: int")
lines.append("    blocks: list[OCRBlock]")
lines.append("    full_text: str")
lines.append("    preprocessed_image: str | None = None")
lines.append("    warnings: list[str] = []")
lines.append("")
lines.append("class OcrMatchResult(BaseModel):")
lines.append("    rank: int")
lines.append("    product_id: str")
lines.append("    product_name: str")
lines.append("    set_name: str")
lines.append("    number: str")
lines.append("    rarity: str")
lines.append("    score: float")
lines.append("    has_image: bool")
lines.append("    product: dict | None = None")
lines.append("")
lines.append("class OcrMatchResponse(BaseModel):")
lines.append("    status: str")
lines.append("    query_text: str")
lines.append("    query_time_ms: float")
lines.append("    preprocessed_image: str | None = None")
lines.append("    warnings: list[str] = []")
lines.append("    results: list[OcrMatchResult]")
lines.append("")
lines.append("# ---- DINOv2 helpers ----")
lines.append("def load_model():")
lines.append("    try:")
lines.append("        m = torch.hub.load(\"facebookresearch/dinov2\", \"dinov2_vitb14\")")
lines.append("    except Exception:")
lines.append("        from transformers import AutoModel")
lines.append("        m = AutoModel.from_pretrained(\"facebook/dinov2-base\")")
lines.append("    m.eval()")
lines.append("    return m")
lines.append("")
lines.append("def to_tensor(img):")
lines.append("    arr = np.asarray(img, dtype=np.float32) / 255.0")
lines.append("    arr = (arr - MEAN) / STD")
lines.append("    return torch.from_numpy(arr.transpose(2, 0, 1)[None]).float()")
lines.append("")
lines.append("@torch.no_grad()")
lines.append("def embed_single(model, img):")
lines.append("    x = to_tensor(img)")
lines.append("    out = model(x)")
lines.append("    if out.dim() == 3:")
lines.append("        out = out[:, 0]")
lines.append("    f = out.numpy().astype(np.float32)")
lines.append("    n = np.linalg.norm(f)")
lines.append("    return f / n if n > 0 else f")
lines.append("")
lines.append("def run_ocr(img_pil):")
lines.append("    \"\"\"Run OCR with 180-deg rotation retry fallback.\"\"\"")
lines.append("    warnings = []")
lines.append("    img_np = np.array(img_pil)")
lines.append("    if img_np.ndim == 2:")
lines.append("        img_bgr = np.stack([img_np] * 3, axis=-1)")
lines.append("    elif img_np.shape[2] == 4:")
lines.append("        img_bgr = img_np[:, :, :3][:, :, ::-1]")
lines.append("    elif img_np.shape[2] == 3:")
lines.append("        img_bgr = img_np[:, :, ::-1]")
lines.append("    else:")
lines.append("        img_bgr = img_np")
lines.append("    img_pp = ocr_preprocessor.preprocess(img_bgr)")
lines.append("    results, elapsed = ocr_engine.read(img_pp)")
lines.append("    full_text = \"\\n\".join(r.text for r in results)")
lines.append("    blocks = [{\"text\": r.text, \"confidence\": r.confidence, \"bbox\": r.bbox} for r in results]")
lines.append("    if len(results) < OCR_RETRY_CONF[\"min_blocks\"] and OCR_RETRY_CONF[\"retry_180\"]:")
lines.append("        from PIL import Image as PILImage")
lines.append("        img_rot = PILImage.fromarray(img_bgr[:, :, ::-1]).rotate(180, expand=True)")
lines.append("        img_rot_np = np.array(img_rot)[:, :, ::-1]")
lines.append("        img_rot_pp = ocr_preprocessor.preprocess(img_rot_np)")
lines.append("        results2, elapsed2 = ocr_engine.read(img_rot_pp)")
lines.append("        if len(results2) > len(results):")
lines.append("            results = results2; elapsed = elapsed2")
lines.append("            full_text = \"\\n\".join(r.text for r in results)")
lines.append("            blocks = [{\"text\": r.text, \"confidence\": r.confidence, \"bbox\": r.bbox} for r in results]")
lines.append("            warnings.append(\"Applied 180-deg rotation fallback for OCR\")")
lines.append("        else:")
lines.append("            warnings.append(\"Low OCR text count, 180-deg rotation did not improve\")")
lines.append("    return blocks, full_text, elapsed, warnings")
lines.append("")
lines.append("# ---- FastAPI app ----")
lines.append("app = FastAPI(title=\"TCG Card Matching Service\", version=\"0.1.0\")")
lines.append("app.add_middleware(CORSMiddleware, allow_origins=[\"*\"], allow_methods=[\"*\"], allow_headers=[\"*\"])")
lines.append("STATIC_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), \"static\")")
lines.append("INDEX_HTML = os.path.join(STATIC_DIR, \"index.html\")")
lines.append("")
lines.append("@app.on_event(\"startup\")")
lines.append("async def startup():")
lines.append("    global model, faiss_index, index_ids, index_version")
lines.append("    global ocr_engine, ocr_preprocessor")
lines.append("    global text_model, text_index, text_ids, products")
lines.append("    t0 = time.time()")
lines.append("    log.info(\"Loading DINOv2 model...\")")
lines.append("    model = load_model()")
lines.append("    log.info(f\"Model loaded in {time.time()-t0:.1f}s\")")
lines.append("    index_dir = os.path.join(ROOT, \"index\")")
lines.append("    index_emb = np.load(os.path.join(index_dir, \"embeddings.npy\"))")
lines.append("    with open(os.path.join(index_dir, \"ids.json\"), \"r\", encoding=\"utf-8\") as f:")
lines.append("        index_ids = json.load(f)")
lines.append("    d = index_emb.shape[1]")
lines.append("    faiss_index = faiss.IndexFlatIP(d)")
lines.append("    faiss_index.add(index_emb)")
lines.append("    index_emb = None")
lines.append("    version_path = os.path.join(index_dir, \"version.txt\")")
lines.append("    if os.path.exists(version_path):")
lines.append("        with open(version_path, \"r\", encoding=\"utf-8\") as f:")
lines.append("            index_version = f.readline().strip()")
lines.append("    else:")
lines.append("        index_version = \"unknown\"")
lines.append("    log.info(f\"Gallery index loaded: {faiss_index.ntotal} vectors, dim={d} ({time.time()-t0:.1f}s total)\")")
lines.append("    log.info(\"Loading OCR preprocessor...\")")
lines.append("    ocr_preprocessor = OCRPreprocessor(max_dim=1200)")
lines.append("    log.info(\"OCR preprocessor loaded\")")
lines.append("    log.info(\"Loading PP-OCRv4 engine...\")")
lines.append("    ocr_engine = PPOCRv4Engine(threads=2)")
lines.append("    log.info(\"PP-OCRv4 engine loaded\")")
lines.append("    t1 = time.time()")
lines.append("    log.info(\"Loading BGE text embedding model...\")")
lines.append("    text_model = SentenceTransformer(BGE_MODEL_NAME, device=\"cpu\")")
lines.append("    log.info(f\"BGE model loaded ({time.time()-t1:.1f}s)\")")
lines.append("    t2 = time.time()")
lines.append("    log.info(\"Loading text index...\")")
lines.append("    text_emb = np.load(os.path.join(TEXT_INDEX_DIR, \"embeddings.npy\"))")
lines.append("    with open(os.path.join(TEXT_INDEX_DIR, \"ids.json\"), \"r\", encoding=\"utf-8\") as f:")
lines.append("        text_ids = json.load(f)")
lines.append("    text_d = text_emb.shape[1]")
lines.append("    text_index = faiss.IndexFlatIP(text_d)")
lines.append("    text_index.add(text_emb)")
lines.append("    text_emb = None")
lines.append("    log.info(f\"Text index loaded: {text_index.ntotal} vectors, dim={text_d} ({time.time()-t2:.1f}s)\")")
lines.append("    t3 = time.time()")
lines.append("    log.info(\"Loading products.jsonl...\")")
lines.append("    products = {}")
lines.append("    with open(PRODUCTS_JSONL, \"r\", encoding=\"utf-8\") as f:")
lines.append("        for line in f:")
lines.append("            d = json.loads(line)")
lines.append("            products[str(d[\"productId\"])] = d")
lines.append("    log.info(f\"Products loaded: {len(products)} records ({time.time()-t3:.1f}s)\")")
lines.append("    log.info(f\"Total startup: {time.time()-t0:.1f}s\")")
lines.append("")
lines.append("@app.get(\"/\")")
lines.append("async def root():")
lines.append("    return FileResponse(INDEX_HTML, media_type=\"text/html\")")
lines.append("")
lines.append("@app.get(\"/v1/health\", response_model=HealthResponse)")
lines.append("async def health():")
lines.append("    return HealthResponse(status=\"ok\", index_size=faiss_index.ntotal if faiss_index is not None else 0, embedding_dim=faiss_index.d if faiss_index is not None else 0, version=index_version)")
lines.append("")
lines.append("@app.post(\"/v1/match\", response_model=MatchResponse)")
lines.append("async def match(file: UploadFile = File(...)):")
lines.append("    t0 = time.time()")
lines.append("    try:")
lines.append("        contents = await file.read()")
lines.append("        if len(contents) == 0:")
lines.append("            raise HTTPException(400, \"Empty file\")")
lines.append("        if len(contents) > MAX_FILE_SIZE:")
lines.append("            raise HTTPException(400, f\"File too large (max {MAX_FILE_SIZE // 1024 // 1024}MB)\")")
lines.append("        if file.content_type and not file.content_type.startswith(\"image/\"):")
lines.append("            raise HTTPException(400, \"Only image files are supported\")")
lines.append("        img = Image.open(io.BytesIO(contents))")
lines.append("        img.load()")
lines.append("        img = preprocess_query(img)")
lines.append("    except HTTPException:")
lines.append("        raise")
lines.append("    except Exception as e:")
lines.append("        raise HTTPException(400, f\"Invalid image: {e}\")")
lines.append("    cands = list(orientation_candidates(img))")
lines.append("    best_score = -1.0; best_idx = -1; best_top2_score = -1.0; best_top2_idx = -1")
lines.append("    for cand in cands:")
lines.append("        inp = to_model_input(cand)")
lines.append("        feat = embed_single(model, inp)")
lines.append("        scores, indices = faiss_index.search(feat.reshape(1, -1), 3)")
lines.append("        s0 = float(scores[0, 0]); s1 = float(scores[0, 1])")
lines.append("        if s0 > best_score:")
lines.append("            best_score = s0; best_idx = int(indices[0, 0]); best_top2_score = s1; best_top2_idx = int(indices[0, 1])")
lines.append("    top1_id = index_ids[best_idx]; top2_id = index_ids[best_top2_idx]; margin = best_score - best_top2_score")
lines.append("    if best_score >= TAU and margin >= MARGIN:")
lines.append("        log.info(f\"MATCH {top1_id} score={best_score:.4f} margin={margin:.4f} ({time.time()-t0:.2f}s)\")")
lines.append("        return MatchResponse(status=\"matched\", card_id=top1_id, score=round(best_score, 4), margin=round(margin, 4), top2_id=top2_id, top2_score=round(best_top2_score, 4))")
lines.append("    log.info(f\"REJECT score={best_score:.4f} margin={margin:.4f} ({time.time()-t0:.2f}s)\")")
lines.append("    return MatchResponse(status=\"rejected\", score=round(best_score, 4), margin=round(margin, 4), top2_id=top2_id if best_score >= TAU else None, top2_score=round(best_top2_score, 4) if best_score >= TAU else None)")
lines.append("")
lines.append("@app.get(\"/v1/images/{card_id}\")")
lines.append("async def get_image(card_id: str):")
lines.append("    if \"..\" in card_id or \"/\" in card_id or \"\\\\\" in card_id:")
lines.append("        raise HTTPException(400, \"Invalid card_id\")")
lines.append("    card_fname = card_id if card_id.endswith(\".jpg\") else card_id + \".jpg\"")
lines.append("    img_path = os.path.join(POKEMON_IMAGES_DIR, card_fname)")
lines.append("    if not os.path.exists(img_path):")
lines.append("        img_path = os.path.join(ROOT, \"images\", card_fname)")
lines.append("    if not os.path.exists(img_path):")
lines.append("        raise HTTPException(404, f\"Image not found: {card_id}\")")
lines.append("    return FileResponse(img_path, media_type=\"image/jpeg\")")
lines.append("")
lines.append("@app.post(\"/v1/search\", response_model=SearchResponse)")
lines.append("async def search(file: UploadFile = File(...)):")
lines.append("    t0 = time.time()")
lines.append("    try:")
lines.append("        contents = await file.read()")
lines.append("        if len(contents) == 0:")
lines.append("            raise HTTPException(400, \"Empty file\")")
lines.append("        if len(contents) > MAX_FILE_SIZE:")
lines.append("            raise HTTPException(400, f\"File too large (max {MAX_FILE_SIZE // 1024 // 1024}MB)\")")
lines.append("        if file.content_type and not file.content_type.startswith(\"image/\"):")
lines.append("            raise HTTPException(400, \"Only image files are supported\")")
lines.append("        img = Image.open(io.BytesIO(contents))")
lines.append("        img.load()")
lines.append("        img = preprocess_query(img)")
lines.append("    except HTTPException:")
lines.append("        raise")
lines.append("    except Exception as e:")
lines.append("        raise HTTPException(400, f\"Invalid image: {e}\")")
lines.append("    cands = list(orientation_candidates(img))")
lines.append("    best_score = -1.0; best_feat = None; best_cand = None")
lines.append("    for cand in cands:")
lines.append("        inp = to_model_input(cand)")
lines.append("        feat = embed_single(model, inp)")
lines.append("        scores, indices = faiss_index.search(feat.reshape(1, -1), 5)")
lines.append("        s0 = float(scores[0, 0])")
lines.append("        if s0 > best_score:")
lines.append("            best_score = s0; best_feat = feat; best_cand = cand")
lines.append("    _buf = io.BytesIO()")
lines.append("    best_cand.save(_buf, format=\"JPEG\", quality=85)")
lines.append("    preprocessed_b64 = base64.b64encode(_buf.getvalue()).decode()")
lines.append("    scores, indices = faiss_index.search(best_feat.reshape(1, -1), 5)")
lines.append("    elapsed = (time.time() - t0) * 1000")
lines.append("    results = []")
lines.append("    for k in range(5):")
lines.append("        card_id = index_ids[int(indices[0, k])]")
lines.append("        results.append(SearchResult(rank=k + 1, card_id=card_id, score=round(float(scores[0, k]), 4)))")
lines.append("    log.info(f\"SEARCH top1={results[0].card_id} score={results[0].score:.4f} ({elapsed:.0f}ms)\")")
lines.append("    return SearchResponse(status=\"ok\", query_time_ms=round(elapsed, 1), results=results, preprocessed_image=preprocessed_b64)")
lines.append("")
lines.append("@app.post(\"/v1/ocr\", response_model=OCRResponse)")
lines.append("async def ocr(file: UploadFile = File(...)):")
lines.append("    t0 = time.time()")
lines.append("    try:")
lines.append("        contents = await file.read()")
lines.append("        if len(contents) == 0:")
lines.append("            raise HTTPException(400, \"Empty file\")")
lines.append("        if len(contents) > MAX_FILE_SIZE:")
lines.append("            raise HTTPException(400, f\"File too large (max {MAX_FILE_SIZE // 1024 // 1024}MB)\")")
lines.append("        if file.content_type and not file.content_type.startswith(\"image/\"):")
lines.append("            raise HTTPException(400, \"Only image files are supported\")")
lines.append("        img = Image.open(io.BytesIO(contents))")
lines.append("        img.load()")
lines.append("        img = preprocess_query(img)")
lines.append("    except HTTPException:")
lines.append("        raise")
lines.append("    except Exception as e:")
lines.append("        raise HTTPException(400, f\"Invalid image: {e}\")")
lines.append("    blocks, full_text, ocr_elapsed, warnings = run_ocr(img)")
lines.append("    _buf = io.BytesIO()")
lines.append("    img.save(_buf, format=\"JPEG\", quality=85)")
lines.append("    preprocessed_b64 = base64.b64encode(_buf.getvalue()).decode()")
lines.append("    ocr_blocks = [OCRBlock(text=b[\"text\"], confidence=b[\"confidence\"], bbox=b[\"bbox\"]) for b in blocks]")
lines.append("    log.info(f\"OCR {len(blocks)} blocks ({ocr_elapsed*1000:.0f}ms)\")")
lines.append("    return OCRResponse(status=\"ok\", ocr_time_ms=round(ocr_elapsed * 1000, 1), total_blocks=len(blocks), blocks=ocr_blocks, full_text=full_text, preprocessed_image=preprocessed_b64, warnings=warnings)")
lines.append("")
lines.append("@app.post(\"/v1/ocr-match\", response_model=OcrMatchResponse)")
lines.append("async def ocr_match(file: UploadFile = File(...)):")
lines.append("    t0 = time.time()")
lines.append("    try:")
lines.append("        contents = await file.read()")
lines.append("        if len(contents) == 0:")
lines.append("            raise HTTPException(400, \"Empty file\")")
lines.append("        if len(contents) > MAX_FILE_SIZE:")
lines.append("            raise HTTPException(400, f\"File too large (max {MAX_FILE_SIZE // 1024 // 1024}MB)\")")
lines.append("        if file.content_type and not file.content_type.startswith(\"image/\"):")
lines.append("            raise HTTPException(400, \"Only image files are supported\")")
lines.append("        img = Image.open(io.BytesIO(contents))")
lines.append("        img.load()")
lines.append("    except HTTPException:")
lines.append("        raise")
lines.append("    except Exception as e:")
lines.append("        raise HTTPException(400, f\"Invalid image: {e}\")")
lines.append("    img_pp = preprocess_for_ocr(img)")
lines.append("    _buf = io.BytesIO()")
lines.append("    img_pp.save(_buf, format=\"JPEG\", quality=85)")
lines.append("    preprocessed_b64 = base64.b64encode(_buf.getvalue()).decode()")
lines.append("    blocks, full_text, ocr_elapsed, warnings = run_ocr(img_pp)")
lines.append("    if not full_text.strip():")
lines.append("        return OcrMatchResponse(status=\"ok\", query_text=\"\", query_time_ms=round((time.time() - t0) * 1000, 1), preprocessed_image=preprocessed_b64, warnings=[\"OCR returned no text\"], results=[])")
lines.append("    query_text = BGE_QUERY_PREFIX + full_text.strip()")
lines.append("    q_emb = text_model.encode(query_text, normalize_embeddings=True).astype(np.float32)")
lines.append("    scores, indices = text_index.search(q_emb.reshape(1, -1), 5)")
lines.append("    results = []")
lines.append("    for k in range(5):")
lines.append("        pid = text_ids[int(indices[0, k])]")
lines.append("        score = float(scores[0, k])")
lines.append("        prod = products.get(pid, {})")
lines.append("        prod_name = prod.get(\"productName\", pid)")
lines.append("        set_name = prod.get(\"setName\", \"\")")
lines.append("        number = prod.get(\"customAttributes\", {}).get(\"number\", \"\") if prod.get(\"customAttributes\") else \"\"")
lines.append("        rarity = prod.get(\"rarityName\", \"\")")
lines.append("        has_image = os.path.exists(os.path.join(POKEMON_IMAGES_DIR, f\"{pid}_200w.jpg\"))")
lines.append("        results.append(OcrMatchResult(rank=k + 1, product_id=pid, product_name=prod_name, set_name=set_name, number=number, rarity=rarity, score=score, has_image=has_image, product=prod if prod else None))")
lines.append("    elapsed = (time.time() - t0) * 1000")
lines.append("    log.info(f\"OCR-MATCH top1={results[0].product_id} score={results[0].score:.4f} ({elapsed:.0f}ms)\")")
lines.append("    return OcrMatchResponse(status=\"ok\", query_text=full_text.strip(), query_time_ms=round(elapsed, 1), preprocessed_image=preprocessed_b64, warnings=warnings, results=results)")
lines.append("")
lines.append("if __name__ == \"__main__\":")
lines.append("    uvicorn.run(app, host=\"0.0.0.0\", port=8056)")

new_content = "\n".join(lines)
with open("app/main.py", "w", encoding="utf-8") as f:
    f.write(new_content)
print(f"Wrote {len(lines)} lines")
